# Generated by Django 5.2.5 on 2025-08-12 12:38

import datetime
import django.utils.timezone
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=datetime.date(2025, 8, 19)),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(
                default=payments.models.generate_invoice_number,
                max_length=50,
                unique=True,
            ),
        ),
    ]
