# Generated by Django 5.2.5 on 2025-08-13 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_invoice_due_date_alter_invoice_issue_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=datetime.date(2025, 8, 20)),
        ),
    ]
