# Generated by Django 5.2.5 on 2025-09-16 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_invoice_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=datetime.date(2025, 9, 23)),
        ),
    ]
