# Generated by Django 5.2.5 on 2025-08-10 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: +8801234567890. Up to 15 digits allowed.",
                        regex="^\\+8801\\d{9}$",
                    )
                ],
            ),
        ),
    ]
