# Generated by Django 5.2.5 on 2025-08-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="present",
            field=models.BooleanField(default=True),
        ),
    ]
