# Generated by Django 5.2.5 on 2025-08-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_attendance_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessclass",
            name="price_cents",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
