# Generated by Django 5.2.5 on 2025-09-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_fitnessclass_price_cents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("CANCELLED", "Cancelled"),
                    ("ATTENDED", "Attended"),
                    ("NO_SHOW", "No Show"),
                ],
                default="NO_SHOW",
                max_length=10,
            ),
        ),
    ]
