# Generated by Django 5.2.5 on 2025-08-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_generatepaymentreport_delete_paymentreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackreport",
            name="generated_by",
        ),
        migrations.RemoveField(
            model_name="generatepaymentreport",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="generatepaymentreport",
            name="member",
        ),
        migrations.RemoveField(
            model_name="membershipreport",
            name="generated_by",
        ),
        migrations.DeleteModel(
            name="AttendanceReport",
        ),
        migrations.DeleteModel(
            name="FeedbackReport",
        ),
        migrations.DeleteModel(
            name="GeneratePaymentReport",
        ),
        migrations.DeleteModel(
            name="MembershipReport",
        ),
    ]
